*** FE - Model

cap lab var sh_tof_wo_b "Share of plot area allocated to trees on farms (excluding bananas) (proportion)"
cap lab var sh_tof_w_b "Share of plot area allocated to trees on farms (including bananas) (proportion)"
cap lab var sh_fruit_wo_b "Share of plot area allocated to fruit trees (excluding bananas) (proportion)"
cap lab var sh_fruit_w_b "Share of plot area allocated to fruit trees (including bananas) (proportion)"
cap lab var sh_cash "Share of plot area allocated to tree cash crops (proportion)"
cap lab var tot_exp "Total monthly household consumption per adult equivalent (constant 2010 UGX$) (in 10,000)"
cap lab var exp_food "Total monthly household food consumption per adult equivalent (constant 2010 UGX$)"
cap lab var exp_durable "Total monthly household consumption (durable goods per adult equivalent) (constant 2010 UGX$)"
cap lab var exp_nodurable "Total monthly household consumption (non-durable goods per adult equivalent) (constant 2010 UGX$)"
cap lab var hhsize_ae "Household size (adult equivalent)"
cap lab var dep_ratio "Dependency ratio"
cap lab var hh_head_age "Household head age (years)"
cap lab var hh_head_sex "Household head sex (female = 1)"
cap lab var land_size "Land owned (ha)"
cap lab var lvst_large "Number of large ruminants"
cap lab var lvst_small "Number of small ruminants"

*** Nutrition
cap lab var share_treesonfarm "Share gross agricultural income from trees on farms (proportion)"
cap lab var share_fruit "Share gross agricultural income from fruit trees"
cap lab var cpexp30 "Monthly Household Expenditures, Spatially/Temporally Adjusted in 11/12"
cap lab var poor_13 "Poverty Status (below the poverty line) (yes = 1)"
cap lab var ch_sex "Sex of Child (female = 1)"
cap lab var ch_age_m "Age of child (in months)"
cap lab var ch_age_m_sq "Age of child (in months) (squared)"
cap lab var mcg_age "Age of main caregiver (years)"
cap lab var mcg_age_sq "Age of main caregiver (years, squared)""
cap lab var mcg_sex "Sex of main caregiver (female = 1)"
cap lab var mcg_sch "Education level of main caregiver"
cap lab var hhsize_ae "Household size (adult equivalent)"
cap lab var dep_ratio "Dependency ratio"
cap lab var lvst_large "Number of large ruminants"
cap lab var lvst_small "Number of small ruminants"
