lab var new_treeonfarm "New Adopter of Trees On Farm"
lab var always_treeonfarm "Always with Trees On Farm"
lab var drop_treeonfarm "Drop-out Trees On Farm"
lab var new_cash "New Adopter of Tree Cash Crops"
lab var always_cash "Always with Trees Cash Crops"
lab var drop_cash "Drop-out Trees Cash Crops"
lab var new_fruit "New Adopter of Fruit Trees"
lab var always_fruit "Always with Fruit Trees"
lab var drop_fruit "Drop-out Fruit Trees"
lab var migra "Moved Outside Community"
lab var hh_head_age "Household Head Age (2004-05)"
lab var hh_head_sex "Household Head Sex (2004-05)"
lab var ch_hhsize_ae "Change of Household Size (adult equivalent)"
lab var ch_dep_ratio "Change of Dependency Ratio"
lab var ch_lvst_large "Change of Number of Large Ruminants"
lab var ch_lvst_small "Change of Number of Small Ruminants"
lab var ch_land_size_ln "Change of land owned (ha)"
